---
- name: Cau hinh switch
  hosts: all
  gather_facts: no

  tasks:
    - name: show ip
      ios_command: 
        commands: 
          - show ip interfaces brief
      register: output
    - debug: var=ouput.stdout_lines