---
- name: Cau hinh switch
  hosts: cisco
  gather_facts: no
  connection: network_cli

  tasks:
  - name: show ip
    ios_command: 
      commands: 
        - sh ip int bri
    register: output

  - name: data
    debug: var=ip_interface_facts