---
- name: Cau hinh switch
  hosts: all
  gather_facts: no
  tasks:
    - name: show ip
      cisco.ios.ios_command: 
        commands: sh ip int bri
      register: output
    - debug: var=output.stdout_lines