---
- name: Cau hinh switch
  hosts: all
  gather_facts: no

  tasks:
  - name: show ip
    ios_command: 
      commands: 
        - sh ip int bri
    register: output
    debug: var=ip_interface_facts